### ISSUE TITLE
FBのシェアボタンのリンクがとれてない？タイトルも

### ISSUE THREAD

**Issue by mismith0227** [coderdojo-hommachi/coderdojo-hommachi.github.io#6]
post.htmlで埋め込んでる、このコードがURL出してない。
```
{{ site.baseurl }}{{ post.url }}
```

https://github.com/coderdojo-hommachi/coderdojo-hommachi.github.io/blob/master/_layouts/post.html#L14

このコードは同じファイルのここを参考にしましたが、そもそもここも書き出されてないので意味ないコードかもしれないです。
https://github.com/coderdojo-hommachi/coderdojo-hommachi.github.io/blob/master/_layouts/post.html#L5

**Comment by ogom** [comment]
gatsby に変更した
